name: golden
description: Golden test with devices tools.
version: 0.4.0
homepage: https://github.com/zfx-com/golden

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  golden_toolkit:
    git:
      url: https://github.com/CORDEA/flutter_glove_box
      path: packages/golden_toolkit
flutter:
